FIx mehrfachlog Transportlog
OperationPandoraTrigger/OPT-Server-Mod pull request #128
Opened 2021-03-20 22:18 UTC by GNCLORD-MDB

- [ ] Bug mehrfach log Transport log

2021-03-20 22:19 UTC, GNCLORD-MDB commented
Das sollte als Erstmaßnahme reichen, kannst du @formtapez noch mal testen wenn du willst. 
Den kann dann @Frozen-byte noch einspielen für die Schlacht.

2021-03-21 07:04 UTC, formtapez requested changes
Der Check sollte für bessere Performance besser frühst möglich in der fn_clientInitcbaclassevents.sqf im GetOut Handler geschehen. 
z.B. so:
`
    params ["_vec", "_pos", "_unit"];
    if (player isEqualTo _unit) then
    {
        // logge transport von Spielern
        _this call FUNC(writeTransportDistance);
    };
`

Frozen muss aber erstmal den ungefragten merge von gestern zurücknehmen bevor wir das für die Schlacht pushen können.

2021-03-21 09:56 UTC, formtapez commented on addons/OPT/SHOP/fn_writetransportdistance.sqf
> +if (_pos in ["cargo", "gunner"] and (_dis > MinDistance) and (_unit isEqualTo player)) then
Dann kann diese Änderung ja wieder raus.

2021-03-21 09:58 UTC, formtapez commented
@Frozen-byte merge mal den Revert #129 damit wir hier für die heutige Schlacht weiterkommen.

2021-03-21 13:22 UTC, GNCLORD-MDB commented on addons/OPT/SHOP/fn_writetransportdistance.sqf
> +if (_pos in ["cargo", "gunner"] and (_dis > MinDistance) and (_unit isEqualTo player)) then
ja , habs drin gelassen da nicht schlimm ist.

2021-03-21 13:26 UTC, formtapez commented
@GNCLORD-MDB da #129 nun gemerged ist, müsstest Du nochmal die Konflikte lösen damit es wieder zusammenpasst.

2021-03-21 13:51 UTC, GNCLORD-MDB commented
und wie ?

2021-03-21 13:54 UTC, closed without merging