Give player a visible feedback upon flag capture
OperationPandoraTrigger/OPT-Server-Mod pull request #155
Opened 2021-04-27 20:49 UTC by DragonGER

s. title

2021-04-28 05:42 UTC, formtapez requested changes
Benutz mal bitte MLOC() und trag die Übersetzungen in der CfgCLibLocalisation.hpp ein.
Und können wir das vielleicht über systemChat melden? Ich bin kein großer Fan des riesigen und ewig eingeblendeten Hints 😀

2021-04-28 12:17 UTC, DragonGER commented
Ich habe noch einen Sound hinzugefügt, der meiner Meinung nach gut passen würde.
Systemchat und MLOC() habe ich eingebaut.

2021-04-28 13:58 UTC, formtapez commented
Okay, danke. Ich vergaß leider das MLOC alleine nicht ausreicht. Bitte mache
`systemChat format ["%1", MLOC(FLAG_CAPTURED)];`
daraus. Und hintendran den Zeilenvorschub nicht vergessen - damit ich ruhig schlafen kann.

Die Idee mit dem Audiofeedback finde ich gut - Allerdings finde ich den gewählten "Fail"-Sound eher unpassend. Wenn man sich unter Lebensgefahr an die Fahne gekämpft hat und voller Adrenalin die Schnur zieht will man was anderes hören als dieses "Zonk" Versagergeräusch. Gibts ein freundliches "Bing" oder so? 😁

Was halten denn @GNCLORD-MDB und @Frozen-byte von der Audio-Sache?

2021-04-28 14:39 UTC, Frozen-byte commented
> Was halten denn @GNCLORD-MDB und @Frozen-byte von der Audio-Sache?

Ist das auch für alle Hörbar? Wäre meiner Meinung nach ein toller Zusatz. Möchte mir den Sound `addItemFailed` aber vorher einmal anhören.

2021-04-28 15:34 UTC, GNCLORD-MDB commented
Bevor so was eingebaut wird sollten wir uns erster die Freigabe vom Konzept team holen. 
Denn das hatte ja ne Grund wieso wir keine Meldungen mehr über den Fahnenstatus mehr drin haben. 
Ob wir ne Sound brauchen weiß ich nicht, der Könnte einige stören.

2021-04-28 16:27 UTC, formtapez commented
Sound und Meldung sind soweit ich weiß nur lokal bei dem der die Fahne zieht zu sehen und zu hören.
Der Sound "additemok" ist besser - Nur ein kurzer Pieps...

2021-04-28 16:55 UTC, GNCLORD-MDB commented
mmmh könnte man machen dann, verändert dann ja nix zum jetzigen Stand, mal die Antwort abwarten.

2021-04-28 16:56 UTC, DragonGER commented
Ich fand den Sound am passsensten, aber lasst euch nicht vom Namen täuschen.
Brauchen wir für sowas wirklich das Konzepteam?

2021-04-28 16:57 UTC, DragonGER commented
Man könnte den Sound für alle im Umkreis Hörbar machen, aber hier ist wie oben angemerkt nur für denjenigen hörbar, der die Fahne zieht. Ist auch so gedacht gewesen, damit man nicht erst immer hochsehen muss, ob man sie wirklich erwischt hat.
Außerdem ist der Sound mit playSound nicht 3D positionieret.

2021-04-28 16:58 UTC, GNCLORD-MDB commented
naja ein grüner Baum muss auch nachher ein Grüner Baum sein und keine Rote Rose, ob ne Tanne oder ne Fichte ist dann egal :-)

2021-04-28 17:00 UTC, Frozen-byte commented
> Man könnte den Sound für alle im Umkreis Hörbar machen, aber hier ist wie oben angemerkt nur für denjenigen hörbar, der die Fahne zieht. Ist auch so gedacht gewesen, damit man nicht erst immer hochsehen muss, ob man sie wirklich erwischt hat.
Außerdem ist der Sound mit playSound nicht 3D positionieret.

Okay aber ich vermute, dass es keinen großen Aufwand erzeugt, also ein audio-feedback finde ich super. Erstmal einbauen und schauen wie das ankommt.

2021-04-28 17:08 UTC, DragonGER commented
> > Man könnte den Sound für alle im Umkreis Hörbar machen, aber hier ist wie oben angemerkt nur für denjenigen hörbar, der die Fahne zieht. Ist auch so gedacht gewesen, damit man nicht erst immer hochsehen muss, ob man sie wirklich erwischt hat.
> > Außerdem ist der Sound mit playSound nicht 3D positionieret.
> 
> Okay aber ich vermute, dass es keinen großen Aufwand erzeugt, also ein audio-feedback finde ich super. Erstmal einbauen und schauen wie das ankommt.

Ja könnte ich machen, für alle der eigenen Fraktion oder auch für die Gegner?

Und apropos Sound, wenn wir über den Sound streiten packe ich die Fanfare in die Client Mod :P

2021-04-28 17:29 UTC, GNCLORD-MDB commented
Wir schauen mal wie da die Meinung des Konzeptteam ist, bisher gibt da keine Positive Rückmeldung.

2021-06-09 17:30 UTC, formtapez commented
Das Thema wurde vom Konzeptteam leider abgelehnt:
https://opt4.net/forum/index.php?thread/5108-fahneziehen-optisch-und-aktutisch/&postID=102570#post102570

2021-06-09 17:30 UTC, closed without merging

2021-06-09 20:22 UTC, DragonGER commented
Dann halt keinen Mehrgewinn, dem allheiligen Konzeptteam sei dank  ¯\_(ツ)_/¯

2021-06-10 12:03 UTC, GNCLORD-MDB commented
Auf jeden fall dank für die Arbeit die du dir gemacht hast. 
Wenn du weiter ambitionen hast uns zu helfen kannst dich ja mal melden.

2021-06-11 08:54 UTC, Frozen-byte commented
sehr schade 😢 Fand es ein gutes QoL Feature